#!/usr/bin/env bash
# APKAM enrollment for NoPorts on Cisco IOS-XE: cuts new, scope-limited keys
# for this switch ON the switch — no atKeys file is ever copied to it.
#
# Configure the app first (DEVICE_ATSIGN, DEVICE_NAME, ROOT_SERVER if using
# a proxy — see the README), then from the IOS-XE exec prompt:
#
#   Switch# app-hosting connect appid noports session
#   / # onboard-noports.sh <passcode>
#
# where <passcode> is an OTP or SPP generated by an administrator with an
# already-authorized key for the device atSign, e.g. on their machine:
#
#   at_activate otp -a @mydevice          # one-time passcode, or
#   at_activate spp -a @mydevice -s <passcode> -e 1d
#
# While this script waits, the administrator approves the request:
#
#   at_activate approve -a @mydevice --arx noports --drx <device-name>
#
# On approval the APKAM keys are written to the persistent /data volume and
# the entrypoint (which polls for the keys) starts sshnpd automatically.
set -euo pipefail

AT_ACTIVATE_BIN="${AT_ACTIVATE_BIN:-/usr/local/bin/at_activate}"
DATA_DIR="${DATA_DIR:-/data}"

# The entrypoint snapshots its env-var config here; source it in case the
# `app-hosting connect` session shell did not inherit the container env.
if [ -f "${DATA_DIR}/noports.env" ]; then
    # shellcheck source=/dev/null
    . "${DATA_DIR}/noports.env"
fi

DEVICE_ATSIGN="${DEVICE_ATSIGN:-}"
DEVICE_NAME="${DEVICE_NAME:-}"
ROOT_SERVER="${ROOT_SERVER:-}"
KEY_FILE="${KEY_FILE:-${DATA_DIR}/keys/${DEVICE_ATSIGN}_key.atKeys}"

if [ -z "$DEVICE_ATSIGN" ] || [ -z "$DEVICE_NAME" ]; then
    echo "onboard: DEVICE_ATSIGN / DEVICE_NAME not configured." >&2
    echo "Configure the app first from the IOS-XE CLI, e.g.:" >&2
    echo '  app-hosting appid noports' >&2
    echo '   app-resource docker' >&2
    # shellcheck disable=SC2016 # $(APP_DATA) is literal IOS-XE CLI syntax
    echo '    run-opts 1 "-v $(APP_DATA):/data"' >&2
    echo '    run-opts 2 "-e DEVICE_ATSIGN=@mydevice -e MANAGER_ATSIGN=@manager -e DEVICE_NAME=cat9k-1"' >&2
    echo "then restart the app and re-run this script." >&2
    exit 1
fi

PASSCODE="${1:-}"
if [ -z "$PASSCODE" ]; then
    read -r -s -p "Enrollment passcode (OTP/SPP) for ${DEVICE_ATSIGN}: " PASSCODE
    echo
fi

if [ -f "$KEY_FILE" ]; then
    echo "onboard: $KEY_FILE already exists; delete it first to re-enroll" >&2
    exit 1
fi

export HOME="$DATA_DIR"
mkdir -p "$(dirname "$KEY_FILE")"

echo "Requesting APKAM enrollment for ${DEVICE_ATSIGN} (device ${DEVICE_NAME})..."
echo "Approve it from an authorized client, e.g.:"
echo "  at_activate approve -a ${DEVICE_ATSIGN} --arx noports --drx ${DEVICE_NAME}"

# Enrollment traffic egresses via the container's management vNIC, honoring
# ROOT_SERVER (proxy:host:443 form included) — the same path sshnpd uses.
ENROLL_ARGS=(
    --atsign "$DEVICE_ATSIGN"
    --passcode "$PASSCODE"
    --app noports
    --device "$DEVICE_NAME"
    --namespaces "sshnp:rw,sshrvd:rw"
    --keys "$KEY_FILE"
)
if [ -n "$ROOT_SERVER" ]; then
    ENROLL_ARGS+=(--root-server "$ROOT_SERVER")
fi
"$AT_ACTIVATE_BIN" enroll "${ENROLL_ARGS[@]}"

chmod 0600 "$KEY_FILE"
echo
echo "Enrollment complete; APKAM keys written to $KEY_FILE"
echo "The entrypoint will detect the keys and start sshnpd within ~15s."
echo "Check from the IOS-XE CLI:  show app-hosting detail appid noports"
